devscript: line-terminations, continuations

diff --git a/developer/bin/develop_brew_cask b/developer/bin/develop_brew_cask
--- a/developer/bin/develop_brew_cask
+++ b/developer/bin/develop_brew_cask
@@ -3,9 +3,9 @@
 # develop_brew_cask
 #
 
-set -e;               # exit on any uncaught error
-set +o histexpand;    # don't expand history expressions
-shopt -s nocasematch; # case-insensitive regular expressions
+set -e               # exit on any uncaught error
+set +o histexpand    # don't expand history expressions
+shopt -s nocasematch # case-insensitive regular expressions
 
 cd_to_project_root () {
     local script_dir="$(/usr/bin/dirname $0)"
@@ -13,7 +13,7 @@ cd_to_project_root () {
     local git_root="$(git rev-parse --show-toplevel)"
     if [[ -z "$git_root" ]]; then
         printf "Could not find git project root"
-        exit 1;
+        exit 1
     fi
     cd "$git_root"
 }
@@ -22,8 +22,8 @@ cd_to_version_dir () {
     local cellar_dir="$1"
     local version_dir="$2"
     if [[ -z "$version_dir" ]]; then
-        printf "Can't get version dir under $cellar_dir/\n";
-        exit 1;
+        printf "Can't get version dir under $cellar_dir/\n"
+        exit 1
     fi
     cd "$cellar_dir/$version_dir"
 }
@@ -48,7 +48,7 @@ _develop_brew_cask () {
     local tap_subdir="Library/Taps/phinze-cask"
 
     # initialization
-    cd_to_project_root;
+    cd_to_project_root
     local git_root="$(pwd)"
     local brew_prefix="$(brew --prefix)"
     local cellar_dir="$brew_prefix/Cellar/brew-cask"
@@ -57,17 +57,17 @@ _develop_brew_cask () {
 
     # sanity check
     if [[ "$(/usr/bin/stat -L -f '%i' "$tap_dir")" -eq "$(/usr/bin/stat -L -f '%i' "$git_root")" ]]; then
-        printf "\nERROR: run this script in your private repo, not inside Homebrew.\n";
-        exit 1;
+        printf "\nERROR: run this script in your private repo, not inside Homebrew.\n"
+        exit 1
     fi
 
     # action
-    cd_to_version_dir "$cellar_dir" "$version_dir";
+    cd_to_version_dir "$cellar_dir" "$version_dir"
     if [[ -e "production_rubylib" ]]; then
-        printf "brew-cask is already set up for development\n";
+        printf "brew-cask is already set up for development\n"
         exit 1
     else
-        create_dev_links "$git_root" "$tap_dir";
+        create_dev_links "$git_root" "$tap_dir"
         printf "brew-cask is now in development mode\n"
         printf "Note: it is not safe to run 'brew update' while in development mode\n"
     fi
@@ -92,6 +92,6 @@ mode is in effect.
     exit
 fi
 
-_develop_brew_cask "$@";
+_develop_brew_cask "$@"
 
 #
diff --git a/developer/bin/get_release_tag b/developer/bin/get_release_tag
--- a/developer/bin/get_release_tag
+++ b/developer/bin/get_release_tag
@@ -3,16 +3,16 @@
 # get_release_tag
 #
 
-set -e;               # exit on any uncaught error
-set +o histexpand;    # don't expand history expressions
-shopt -s nocasematch; # case-insensitive regular expressions
+set -e               # exit on any uncaught error
+set +o histexpand    # don't expand history expressions
+shopt -s nocasematch # case-insensitive regular expressions
 
-opt_next='';
-opt_latest='';
-opt_verbose='';
+opt_next=''
+opt_latest=''
+opt_verbose=''
 
 die () {
-    local message="$@";
+    local message="$@"
     if ! [[ $message =~ "\n"$ ]]; then
         message="${message}\n"
     fi
@@ -71,7 +71,7 @@ generate_next_major_tag () {
 
 generate_next_minor_tag () {
     local -a version_elts
-    IFS='.' read -a version_elts <<< "$1";
+    IFS='.' read -a version_elts <<< "$1"
     sanity_check_parsed_version "${version_elts[@]}"
     (( version_elts[1] += 1 ))      # increment minor field
     version_elts[2]='0'             # reset patch field
@@ -123,12 +123,12 @@ See RELEASING.md for more information.
             fi
         elif [[ $arg =~ ^-+patch$ ]]; then
             if [[ "$opt_next" == 'major' ]]; then
-                die "Error: -patch is incompatible with -major";
+                die "Error: -patch is incompatible with -major"
             fi
             opt_next='patch'
         elif [[ $arg =~ ^-+major$ ]]; then
             if [[ "$opt_next" == 'patch' ]]; then
-                die "Error: -patch is incompatible with -major";
+                die "Error: -patch is incompatible with -major"
             fi
             opt_next='major'
         elif [[ $arg =~ ^-+latest$ ]]; then
@@ -143,7 +143,7 @@ See RELEASING.md for more information.
 }
 
 _get_release_tag () {
-    cd_to_project_root;
+    cd_to_project_root
     local latest_tag="$(git describe --tags --abbrev=0 2>/dev/null)"
     if [[ -z "$latest_tag" ]]; then
         die "Error: no recent tag found"
@@ -163,8 +163,8 @@ _get_release_tag () {
     fi
 }
 
-process_args "$@";
+process_args "$@"
 
-_get_release_tag;
+_get_release_tag
 
 #
diff --git a/developer/bin/production_brew_cask b/developer/bin/production_brew_cask
--- a/developer/bin/production_brew_cask
+++ b/developer/bin/production_brew_cask
@@ -3,9 +3,9 @@
 # production_brew_cask
 #
 
-set -e;               # exit on any uncaught error
-set +o histexpand;    # don't expand history expressions
-shopt -s nocasematch; # case-insensitive regular expressions
+set -e               # exit on any uncaught error
+set +o histexpand    # don't expand history expressions
+shopt -s nocasematch # case-insensitive regular expressions
 
 cd_to_project_root () {
     local script_dir="$(/usr/bin/dirname $0)"
@@ -13,7 +13,7 @@ cd_to_project_root () {
     local git_root="$(git rev-parse --show-toplevel)"
     if [[ -z "$git_root" ]]; then
         printf "Could not find git project root"
-        exit 1;
+        exit 1
     fi
     cd "$git_root"
 }
@@ -22,8 +22,8 @@ cd_to_version_dir () {
     local cellar_dir="$1"
     local version_dir="$2"
     if [[ -z "$version_dir" ]]; then
-        printf "Can't get version dir under $cellar_dir/\n";
-        exit 1;
+        printf "Can't get version dir under $cellar_dir/\n"
+        exit 1
     fi
     cd "$cellar_dir/$version_dir"
 }
@@ -45,7 +45,7 @@ _production_brew_cask () {
     local tap_subdir="Library/Taps/phinze-cask"
 
     # initialization
-    cd_to_project_root;
+    cd_to_project_root
     local git_root="$(pwd)"
     local brew_prefix="$(brew --prefix)"
     local cellar_dir="$brew_prefix/Cellar/brew-cask"
@@ -55,13 +55,13 @@ _production_brew_cask () {
     # sanity check
     if [[ "$(/usr/bin/stat -L -f '%i' "$tap_dir")" -eq "$(/usr/bin/stat -L -f '%i' "$git_root")" ]]; then
         printf "\nERROR: run this script in your private repo, not inside Homebrew.\n"
-        exit 1;
+        exit 1
     fi
 
     # action
-    cd_to_version_dir "$cellar_dir" "$version_dir";
+    cd_to_version_dir "$cellar_dir" "$version_dir"
     if [[ -e "production_rubylib" ]]; then
-        remove_dev_links "$tap_dir";
+        remove_dev_links "$tap_dir"
         printf "brew-cask is now in production mode\n"
         printf "It is safe to run 'brew update'\n"
     else
@@ -84,6 +84,6 @@ After running this command it is safe to run 'brew update'.
     exit
 fi
 
-_production_brew_cask "$@";
+_production_brew_cask "$@"
 
 #
