quoting/stdization/full-paths

diff --git a/developer/bin/generate_man_pages b/developer/bin/generate_man_pages
--- a/developer/bin/generate_man_pages
+++ b/developer/bin/generate_man_pages
@@ -5,22 +5,46 @@
 # This is temporary, should be replaced with a Rakefile target
 #
 
-set -e;                # exit on uncaught error
-set +o histexpand;     # don't expand history expressions
-shopt -s nocasematch;  # case-insensitive regular expressions
+###
+### settings
+###
+
+set -e                # exit on uncaught error
+set +o histexpand     # don't expand history expressions
+shopt -s nocasematch  # case-insensitive regular expressions
+
+###
+### functions
+###
+
+warn () {
+    local message="$@"
+    if ! [[ $message =~ "\n"$ ]]; then
+        message="${message}\n"
+    fi
+    printf "$message" 1>&2
+}
+
+die () {
+    warn "$@"
+    exit 1
+}
 
 cd_to_project_root () {
-    local script_dir="$(/usr/bin/dirname $0)"
+    local script_dir="$(/usr/bin/dirname "$0")"
     cd "$script_dir"
     local git_root="$(git rev-parse --show-toplevel)"
     if [[ -z "$git_root" ]]; then
-        printf "Could not find git project root"
-        exit 1;
+        die "ERROR: Could not find git project root"
     fi
     cd "$git_root"
 }
 
-cd_to_project_root;
+###
+### main
+###
+
+cd_to_project_root
 
 ronn --roff --pipe --organization='Homebrew-cask' --manual='brew-cask' doc/src/brew-cask.1.md > doc/man/brew-cask.1
 
