detect ronn requirement

diff --git a/developer/bin/generate_man_pages b/developer/bin/generate_man_pages
--- a/developer/bin/generate_man_pages
+++ b/developer/bin/generate_man_pages
@@ -46,6 +46,10 @@ cd_to_project_root () {
 
 cd_to_project_root
 
+if ! /usr/bin/which ronn >/dev/null 2>&1; then
+    die "ERROR: The 'ronn' gem must be installed"
+fi
+
 ronn --roff --pipe --organization='Homebrew-cask' --manual='brew-cask' doc/src/brew-cask.1.md > doc/man/brew-cask.1
 
 #
